CREATE TABLE `Users` (
	`Name` VARCHAR(255) NOT NULL,
	`SecondName` VARCHAR(255) NOT NULL,
	`MiddleName` VARCHAR(255) NOT NULL,
	`Age` INT NOT NULL,
	`Gender` BOOLEAN NOT NULL,
	`DateOfBirth` DATE NOT NULL,
	`INN` VARCHAR(255) NOT NULL,
	`PostCode` VARCHAR(255) NOT NULL,
	`Country` VARCHAR(255) NOT NULL,
	`Region` VARCHAR(255) NOT NULL,
	`City` VARCHAR(255) NOT NULL,
	`Street` VARCHAR(255) NOT NULL,
	`House` INT NOT NULL,
	`Apartment` INT NOT NULL
);